### ISSUE TITLE
update to this ui

### ISSUE THREAD

**Issue by untuned** [gearhead/RuneUI#3]
How would one update from the old RuneUI to this one?  This one seems to be much more progressed than the official one.

**Comment by gearhead** [comment]
This UI is heavily reliant on the OS being in sync with it. To update to this UI, you will need to grab the full image from the forum. The 0.5b UI is part of the image.
[http://www.runeaudio.com/forum/runeaudio-0-5-beta-for-all-raspberry-pi-models-t6532.html](url)

**Comment by untuned** [comment]
> This UI is heavily reliant on the OS being in sync with it. To update to this UI, you will need to grab the full image from the forum. The 0.5b UI is part of the image.
> [http://www.runeaudio.com/forum/runeaudio-0-5-beta-for-all-raspberry-pi-models-t6532.html](url)

Yeah, I noticed that way after seeing this repo.  Thanks for the help anyway.
