### ISSUE TITLE
Lyrics do not update correctly

### ISSUE THREAD

**Issue by gearhead** [gearhead/RuneUI#8]
If a song is playing and the [i] is selected on the main screen, band info and the song lyrics appear. As long as the next song is not by the same artist, the lyrics will update. If I play an album of songs, the lyrics will not update unless I select a different artist's song then reselect the song I want to listen to. It appears to be related to the artist or album field which triggers a lyric update and not merely a new song playing.

**Comment by janui** [comment]
Fixed in patchversion 8 of  RuneAudio 0.5b

**Comment by gearhead** [comment]
I just pulled and rebooted. still does this. It works great as long as the song is from a different artist or a different album. If the songs are from the same album, the lyrics will not update.
